# Generated by Django 5.1.5 on 2025-02-10 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_devicedatapoints_options'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('total_distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('atual_employee_distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('linked_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            bases=('devices.device',),
        ),
    ]
