# Generated by Django 5.1.5 on 2025-02-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedatapoints',
            old_name='measure',
            new_name='x',
        ),
        migrations.AddField(
            model_name='devicedatapoints',
            name='y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicedatapoints',
            name='z',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
