# Generated by Django 5.1.5 on 2025-02-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_rename_measure_devicedatapoints_x_devicedatapoints_y_and_more'),
        ('employees', '0002_alter_employee_address_alter_employee_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': 'Device Type', 'verbose_name_plural': 'Device Types'},
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='device',
            name='linked_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.CreateModel(
            name='DeviceUserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
