# Generated by Django 5.1.5 on 2025-02-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_devicetype_options_device_linked_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceuserhistory',
            options={'verbose_name': 'Device User History', 'verbose_name_plural': 'Device User Histories'},
        ),
    ]
