# Generated by Django 5.1.5 on 2025-03-08 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_device_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='mac_address',
        ),
    ]
