# Generated by Django 5.1.5 on 2025-03-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_remove_device_mac_address'),
        ('employees', '0003_alter_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='linked_employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='deviceuserhistory',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
