# Generated by Django 5.1.5 on 2025-03-19 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_device_is_active_alter_device_linked_employee_and_more'),
        ('employees', '0003_alter_employee_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='devicedatapoints',
            options={'verbose_name': 'Coordenadas do Dispositivo', 'verbose_name_plural': 'Coordenadas dos Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': 'Tipo de Dispositivo', 'verbose_name_plural': 'Tipos de Dispositivos'},
        ),
        migrations.AlterModelOptions(
            name='deviceuserhistory',
            options={'verbose_name': 'Histórico de Uso do Dispositivo', 'verbose_name_plural': 'Históricos de Uso dos Dispositivos'},
        ),
        migrations.AlterField(
            model_name='device',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype', verbose_name='Tipo de Dispositivo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='device',
            name='linked_employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Funcionário Vinculado'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Dispositivo'),
        ),
        migrations.AlterField(
            model_name='devicedatapoints',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='devicedatapoints',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tipo de Dispositivo'),
        ),
        migrations.AlterField(
            model_name='deviceuserhistory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='deviceuserhistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='deviceuserhistory',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='deviceuserhistory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='deviceuserhistory',
            name='start_date',
            field=models.DateTimeField(verbose_name='Data de Início'),
        ),
    ]
