# Generated by Django 5.1.5 on 2025-02-20 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_address_alter_employee_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='O número de telefone deve ter 10 ou 11 dígitos (apenas números).', regex='^\\d{10,11}$')], verbose_name='Telefone de emergência'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='O número de telefone deve ter 10 ou 11 dígitos (apenas números).', regex='^\\d{10,11}$')], verbose_name='Telefone'),
        ),
    ]
